### ISSUE TITLE
Unable to import a Logical Interconnect Group resource

### ISSUE THREAD

**Issue by jullienl** [HewlettPackard/terraform-provider-oneview#186]
I am using the following in my tf file:
```
resource "oneview_logical_interconnect_group" "logical_interconnect_group" {
}
```
But when I run the terraform import command, terraform crashes (while other resources like LI and network set are successfully imported):

$ terraform import oneview_logical_interconnect_group.logical_interconnect_group LIG-FlexFabric
```
oneview_logical_interconnect_group.logical_interconnect_group: Importing from ID "LIG-FlexFabric"...
oneview_logical_interconnect_group.logical_interconnect_group: Import complete!
  Imported oneview_logical_interconnect_group (ID: LIG-FlexFabric)
oneview_logical_interconnect_group.logical_interconnect_group: Refreshing state... (ID: LIG-FlexFabric)

Error: oneview_logical_interconnect_group.logical_interconnect_group (import id: LIG-FlexFabric): 1 error occurred:
        * import oneview_logical_interconnect_group.logical_interconnect_group result: LIG-FlexFabric: oneview_logical_interconnect_group.logical_interconnect_group: unexpected EOF




panic: runtime error: invalid memory address or nil pointer dereference
2020-06-26T12:03:27.889+0200 [DEBUG] plugin.terraform-provider-oneview: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa2842e]
2020-06-26T12:03:27.889+0200 [DEBUG] plugin.terraform-provider-oneview: 
2020-06-26T12:03:27.889+0200 [DEBUG] plugin.terraform-provider-oneview: goroutine 6 [running]:
2020-06-26T12:03:27.889+0200 [DEBUG] plugin.terraform-provider-oneview: github.com/HewlettPackard/terraform-provider-oneview/oneview.resourceLogicalInterconnectGroupRead(0xc0001f6b60, 0xbbf6e0, 0xc000256780, 0x0, 0x12fb820)
2020-06-26T12:03:27.890+0200 [DEBUG] plugin.terraform-provider-oneview:         /home/lionel/go/src/github.com/HewlettPackard/terraform-provider-oneview/oneview/resource_logical_interconnect_group.go:1476 +0x32be
2020-06-26T12:03:27.890+0200 [DEBUG] plugin.terraform-provider-oneview: github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc00034ab40, 0xc00007a8c0, 0xbbf6e0, 0xc000256780, 0xc000362160, 0x40de01, 0xc0001df920)
2020-06-26T12:03:27.890+0200 [DEBUG] plugin.terraform-provider-oneview:         /home/lionel/go/src/github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:314 +0x16d
2020-06-26T12:03:27.890+0200 [DEBUG] plugin.terraform-provider-oneview: github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc0002d27e0, 0xc00007a870, 0xc00007a8c0, 0xc0001df920, 0xcb75d8, 0xc00024ac00)
2020-06-26T12:03:27.890+0200 [DEBUG] plugin.terraform-provider-oneview:         /home/lionel/go/src/github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:267 +0x8f
2020-06-26T12:03:27.890+0200 [DEBUG] plugin.terraform-provider-oneview: github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc000288640, 0xc000189030, 0xc0001891f0, 0x0, 0x0)
2020-06-26T12:03:27.890+0200 [DEBUG] plugin.terraform-provider-oneview:         /home/lionel/go/src/github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:510 +0x4e
2020-06-26T12:03:27.890+0200 [DEBUG] plugin.terraform-provider-oneview: reflect.Value.call(0xc0002208a0, 0xc000228128, 0x13, 0xc833e2, 0x4, 0xc00024af08, 0x3, 0x3, 0xb5baa0, 0xc0001df2f0, ...)
2020-06-26T12:03:27.890+0200 [DEBUG] plugin.terraform-provider-oneview:         /usr/local/go/src/reflect/value.go:460 +0x8ab
2020-06-26T12:03:27.890+0200 [DEBUG] plugin.terraform-provider-oneview: reflect.Value.Call(0xc0002208a0, 0xc000228128, 0x13, 0xc000055708, 0x3, 0x3, 0xc00009a0b8, 0xc0000383b8, 0x45e850)
2020-06-26T12:03:27.890+0200 [DEBUG] plugin.terraform-provider-oneview:         /usr/local/go/src/reflect/value.go:321 +0xb4
2020-06-26T12:03:27.890+0200 [DEBUG] plugin.terraform-provider-oneview: net/rpc.(*service).call(0xc00022c080, 0xc00024c140, 0xc00022a080, 0xc00022a090, 0xc000256400, 0xc000224a20, 0xb55920, 0xc000189030, 0x16, 0xb55960, ...)
2020-06-26T12:03:27.890+0200 [DEBUG] plugin.terraform-provider-oneview:         /usr/local/go/src/net/rpc/server.go:377 +0x17f
2020-06-26T12:03:27.890+0200 [DEBUG] plugin.terraform-provider-oneview: created by net/rpc.(*Server).ServeCodec
2020-06-26T12:03:27.890+0200 [DEBUG] plugin.terraform-provider-oneview:         /usr/local/go/src/net/rpc/server.go:474 +0x42b
2020/06/26 12:03:27 [ERROR] root: eval: *terraform.EvalRefresh, err: oneview_logical_interconnect_group.logical_interconnect_group: unexpected EOF
2020/06/26 12:03:27 [ERROR] root: eval: *terraform.EvalSequence, err: oneview_logical_interconnect_group.logical_interconnect_group: unexpected EOF
2020/06/26 12:03:27 [TRACE] [walkImport] Exiting eval tree: import oneview_logical_interconnect_group.logical_interconnect_group result: LIG-FlexFabric
2020/06/26 12:03:27 [TRACE] dag/walk: upstream errored, not walking "provider.oneview (close)"
2020-06-26T12:03:27.891+0200 [DEBUG] plugin: plugin process exited: path=/usr/local/bin/terraform-provider-oneview
2020/06/26 12:03:27 [DEBUG] plugin: waiting for all plugin processes to complete...
2020-06-26T12:03:27.892+0200 [WARN ] plugin: error closing client during Kill: err="connection is shut down"



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```
$ terraform -version
Terraform v0.11.14
+ provider.oneview (unversioned)

Your version of Terraform is out of date! The latest version
is 0.12.26. You can update by downloading from www.terraform.io/downloads.html

**Comment by adarobin** [comment]
I can reproduce the same issue with existing code if I increase my API version to 1600.  The error message was most useful, 

`github.com/HewlettPackard/terraform-provider-oneview/oneview/resource_logical_interconnect_group.go:1476 ` is
```go
		"igmp_snooping":           *logicalInterconnectGroup.EthernetSettings.EnableIgmpSnooping,
```

If you look at https://github.com/HewlettPackard/oneview-golang/blob/master/ov/logical_interconnect_group.go (as well as the REST API Reference for 1600) you'll notice that the EnableIgmpSnooping is no longer under the EthernetSettings struct, but is now under the IgmpSettings struct.

**Comment by nabhajit-ray** [comment]
Hi Lionel,

We have fixed this in the latest master. Can you pull it and check if it resolve your issue?

**Comment by jullienl** [comment]
Yes the issue is resolved, thanks a lot

**Comment by jullienl** [comment]
Issue fixed in latest release
