### ISSUE TITLE
Can't create resource oneview_server_profile_template

### ISSUE THREAD

**Issue by Schluggi** [HewlettPackard/terraform-provider-oneview#300]
Hi,

i can't create a oneview_server_profile_template resource. 
First of all, we don't use enclosure groups at all, but the key is required in terraform. Via the webinterface we actually can create Server Profile Templates without an enclosure group.

So i tried to create an empty enclosure group named "empty". But that does not work. The plugin crashes.

Any ideas?

Resource:
```tf
resource "oneview_server_profile_template" "DL360_Gen9_1_legacy" {
  name = "DL360 Gen9 1 legacy"
  enclosure_group = "empty"
  server_hardware_type = "DL360 Gen9 1"
}
```

With empty enclosure group:
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # oneview_server_profile_template.DL360_Gen9_1_legacy will be created
  + resource "oneview_server_profile_template" "DL360_Gen9_1_legacy" {
      + affinity              = "Bay"
      + enclosure_group       = "empty"
      + etag                  = (known after apply)
      + hide_unused_flex_nics = true
      + id                    = (known after apply)
      + mac_type              = "Virtual"
      + name                  = "DL360 Gen9 1 legacy"
      + serial_number_type    = "Virtual"
      + server_hardware_type  = "DL360 Gen9 1"
      + type                  = "ServerProfileTemplateV1"
      + uri                   = (known after apply)
      + wwn_type              = "Virtual"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

oneview_server_profile_template.DL360_Gen9_1_legacy: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with oneview_server_profile_template.DL360_Gen9_1_legacy,
│   on server_profile_template.tf line 1, in resource "oneview_server_profile_template" "DL360_Gen9_1_legacy":
│    1: resource "oneview_server_profile_template" "DL360_Gen9_1_legacy" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-oneview_6.0.0-13.exe plugin:

panic: interface conversion: interface {} is []interface {}, not *schema.Set

goroutine 55 [running]:
github.com/HewlettPackard/terraform-provider-oneview/oneview.resourceServerProfileTemplateCreate(0xc000428690, 0x12eb6c0, 0xc00044e200, 0x2, 0x1c1e9e0)
	github.com/HewlettPackard/terraform-provider-oneview/oneview/resource_server_profile_template.go:1007 +0x7ad9
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000541b80, 0xc000840280, 0xc000488720, 0x12eb6c0, 0xc00044e200, 0x12d9901, 0xc0000b6828, 0xc0006a1320)
	github.com/hashicorp/terraform-plugin-sdk@v1.7.0/helper/schema/resource.go:305 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00017af00, 0xc0005afa10, 0xc000840280, 0xc000488720, 0xc000685ee8, 0xc00059a5d8, 0x12db5c0)
	github.com/hashicorp/terraform-plugin-sdk@v1.7.0/helper/schema/provider.go:294 +0xa5
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00059a0b0, 0x15fec80, 0xc00087e000, 0xc00081c060, 0xc00059a0b0, 0xc00087e000, 0xc000301b78)
	github.com/hashicorp/terraform-plugin-sdk@v1.7.0/internal/helper/plugin/grpc_provider.go:885 +0x8ab
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x13ebd80, 0xc00059a0b0, 0x15fec80, 0xc00087e000, 0xc00081c000, 0x0, 0x15fec80, 0xc00087e000, 0xc00087c000, 0x321)
	github.com/hashicorp/terraform-plugin-sdk@v1.7.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000584600, 0x1608660, 0xc000585200, 0xc0007f2100, 0xc000704510, 0x1bdba40, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.27.1/server.go:1024 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc000584600, 0x1608660, 0xc000585200, 0xc0007f2100, 0x0)
	google.golang.org/grpc@v1.27.1/server.go:1313 +0xd54
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000941e0, 0xc000584600, 0x1608660, 0xc000585200, 0xc0007f2100)
	google.golang.org/grpc@v1.27.1/server.go:722 +0xa8
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.27.1/server.go:720 +0xa8

Error: The terraform-provider-oneview_6.0.0-13.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```
Using terraform 0.15.1 and OneView 6.00.00.

**Comment by AsisBagga** [comment]
@Schluggi Hello Lukas, Thank you for raising this issue, as of now enclosure_group is a required attribute in the provider, and hence the terraform crashes. We will take the necessary actions to address this in our upcoming release.

**Comment by rismoney** [comment]
By the way, thank you @AsisBagga for your quick attention to all the issues.   I will say that server profile/templates are probably the area of most concern for anyone using Oneview.  Most of the other configuration falls into the initial install-time configuration pieces so, whilst important they are not the "moving" pieces you would need to ongoing manage with a config management tool.

If we can get terraform to do the right thing against all the CRUD for server profiles this tool will be far better than managing with ansible, powershell, or any of the others, since folks will be able to declare the state of the infrastructure in a easily composable manner, which I think is a core goal of Synergy.  This will be better than imperatively managing the inf.

Just wanted to lend my gratitude for all the hard work.

**Comment by AsisBagga** [comment]
@rismoney Thank you, we are continuously thriving to make this provider as efficient as possible for our users, thank you for raising issues for getting them to our attention.

**Comment by AsisBagga** [comment]
Since this issue is fixed. Proceeding with closing it.
