### ISSUE TITLE
server profile template resource management discards mp_settings

### ISSUE THREAD

**Issue by BoudewijnSwen** [HewlettPackard/terraform-provider-oneview#446]
I have defined and successfully created an server profile template in my main.tf: 
```
resource "oneview_server_profile_template" "x" {
  name                 = "x"
  description          = "x"
  type                 = "ServerProfileTemplateV8"
  server_hardware_type = "x"
  initial_scope_uris   = [data.oneview_scope.scope.uri]

  firmware {
<omitted>
  }

  bios_option {
<omitted>
  }

  management_processor {
    compliance_control = "Checked"
    manage_mp = true
    mp_settings {
      administrator_account {
        delete_administrator_account = true      
      }
    }
    mp_settings {
      local_accounts {
        display_name = "${upper(var.x_env)} Read-Only User account"
        user_name = "${var.x_env}-ilo-user"
        password = var.ilo_user_password
        ilo_config_priv = false
        remote_console_priv = true
        user_config_priv = false
        virtual_media_priv = false
        virtual_power_and_reset_priv = false
      }
      local_accounts {
        display_name = "${upper(var.x_env)} Admin account"
        user_name = "${var.x_env}-ilo-admin"
        password = var.ilo_admin_password
        ilo_config_priv = true
        remote_console_priv = true
        user_config_priv = true
        virtual_media_priv = true
        virtual_power_and_reset_priv = true
      }
    }
  }

  boot {
<omitted>
  }

  boot_mode {
<omitted>
  }

  san_storage {
<omitted>
  }

  connection_settings {
<omitted>
  }
}
```

If I replan it says its gonna change this part:

```
      ~ management_processor {
          + reapply_state      = ""
            # (2 unchanged attributes hidden)

          ~ mp_settings {
              ~ administrator_account {
                  + delete_administrator_account = true
                }




              - local_accounts {
                  - display_name                 = "X Admin account" -> null
                  - ilo_config_priv              = true -> null
                  - remote_console_priv          = true -> null
                  - user_config_priv             = true -> null
                  - user_name                    = "x-ilo-admin" -> null
                  - virtual_media_priv           = true -> null
                  - virtual_power_and_reset_priv = true -> null
                }
              - local_accounts {
                  - display_name                 = "X Read-Only User account" -> null
                  - ilo_config_priv              = false -> null
                  - remote_console_priv          = true -> null
                  - user_config_priv             = false -> null
                  - user_name                    = "x-ilo-user" -> null
                  - virtual_media_priv           = false -> null
                  - virtual_power_and_reset_priv = false -> null
                }
                # (3 unchanged blocks hidden)
            }
          + mp_settings {
              + administrator_account {
                  + delete_administrator_account = (known after apply)
                  + password                     = (sensitive value)
                }

              + directory {
                  + directory_authentication     = (known after apply)
                  + directory_generic_ldap       = (known after apply)
                  + directory_server_address     = (known after apply)
                  + directory_server_certificate = (known after apply)
                  + directory_server_port        = (known after apply)
                  + directory_user_context       = (known after apply)
                  + ilo_distinguished_name       = (known after apply)
                  + kerberos_authentication      = (known after apply)
                  + kerberos_kdc_server_address  = (known after apply)
                  + kerberos_kdc_server_port     = (known after apply)
                  + kerberos_key_tab             = (known after apply)
                  + kerberos_realm               = (known after apply)
                  + password                     = (sensitive value)
                }

              + ilo_host_name {
                  + hostname = (known after apply)
                }

              + key_manager {
                  + certificate_name         = (known after apply)
                  + group_name               = (known after apply)
                  + login_name               = (known after apply)
                  + password                 = (sensitive value)
                  + primary_server_address   = (known after apply)
                  + primary_server_port      = (known after apply)
                  + redundancy_required      = (known after apply)
                  + secondary_server_address = (known after apply)
                  + secondary_server_port    = (known after apply)
                }

              + local_accounts {
                  # At least one attribute in this block is (or was) sensitive,
                  # so its contents will not be displayed.
                }
            }
        }
```

Reapply gives me: (errors refer to 2 templates, I only posted the config for 1 (x) but there is another one, that is almost the same (y), same issue.

```
2021-12-20T13:14:52.408-0500 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hewlettpackard/oneview/6.4.0-13/linux_amd64/terraform-provider-oneview_v6.4.0-13 pid=24750 error="exit status 2"
2021-12-20T13:14:52.408-0500 [ERROR] plugin.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = transport is closing"
2021-12-20T13:14:52.408-0500 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-12-20T13:14:52.408-0500 [ERROR] plugin.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = transport is closing"
2021-12-20T13:14:52.416-0500 [ERROR] vertex "oneview_server_profile_template.x" error: Plugin did not respond
2021-12-20T13:14:52.421-0500 [ERROR] vertex "oneview_server_profile_template.y" error: Plugin did not respond
╷
│ Error: Plugin did not respond
│ 
│   with oneview_server_profile_template.x,
│   on main.tf line 119, in resource "oneview_server_profile_template" "x":
│  119: resource "oneview_server_profile_template" "x" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with oneview_server_profile_template.y,
│   on main.tf line 230, in resource "oneview_server_profile_template" "y":
│  230: resource "oneview_server_profile_template" "y" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-oneview_v6.4.0-13 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 39 [running]:
github.com/HewlettPackard/terraform-provider-oneview/oneview.resourceServerProfileTemplateUpdate(0xc000681c70, 0x1131040, 0xc000118280, 0x24, 0x1acce80)
        github.com/HewlettPackard/terraform-provider-oneview/oneview/resource_server_profile_template.go:2603 +0xb433
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000624000, 0xc0009a24b0, 0xc000b5b440, 0x1131040, 0xc000118280, 0x111f501, 0xc0002b3a18, 0xc000b95b90)
        github.com/hashicorp/terraform-plugin-sdk@v1.7.0/helper/schema/resource.go:311 +0x273
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000625300, 0xc0007cda10, 0xc0009a24b0, 0xc000b5b440, 0xc0004f67c8, 0xc000a5ae01, 0x1121180)
        github.com/hashicorp/terraform-plugin-sdk@v1.7.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000acd50, 0x1491060, 0xc000a89200, 0xc000702240, 0xc0000acd50, 0xc000a89200, 0xc0007b6b78)
        github.com/hashicorp/terraform-plugin-sdk@v1.7.0/internal/helper/plugin/grpc_provider.go:885 +0x8ab
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1234d80, 0xc0000acd50, 0x1491060, 0xc000a89200, 0xc0007021e0, 0x0, 0x1491060, 0xc000a89200, 0xc000a9c000, 0x2076)
        github.com/hashicorp/terraform-plugin-sdk@v1.7.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000b0d80, 0x149a320, 0xc0000b1c80, 0xc00092a500, 0xc000480810, 0x1a8bb80, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1024 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc0000b0d80, 0x149a320, 0xc0000b1c80, 0xc00092a500, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1313 +0xd34
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000302220, 0xc0000b0d80, 0x149a320, 0xc0000b1c80, 0xc00092a500)
        google.golang.org/grpc@v1.27.1/server.go:722 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.27.1/server.go:720 +0xa5

Error: The terraform-provider-oneview_v6.4.0-13 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2021-12-20T13:14:52.431-0500 [DEBUG] provider: plugin exited
```
There is more debug logs above this, if you need it, I can post it as well.

Using version = "6.4.0-13"  of the terraform provider and my appliance is on 6.40.00-0450507. 

Hopefully someone can help me out! Thanks already.

**Comment by BoudewijnSwen** [comment]
So I have been doing some more testing. Adding the templates and hardware in a separate state. Then adding them as data objects in a new state, to isolate the error.

I have successfully created a profile (no hardware and no template) and then added hardware to this profile. Just creating a profile out of a template seems impossible. 

Full main.tf:
```
# Setup Terraform OneView provider
terraform {
  required_version = ">= 0.13"
  required_providers {
    oneview = {
      source  = "hewlettpackard/oneview"
      version = "6.4.0-13"
    }
  }
}

# Setup local variables
locals {
  ov_endpoint = "https://10.${var.mgt_subnet}.13.37"
}

# Create terraform OneView client
provider "oneview" {
	ov_username   = var.ov_username
	ov_password   = var.ov_password
	ov_endpoint   = local.ov_endpoint
	ov_sslverify  = var.ov_ssl_enabled
	ov_apiversion = var.ov_api_version
	ov_ifmatch    = "*"
}

#### ADD PROFILE ####
data "oneview_scope" "scope" {
  name = var.domain_scope
}

data "oneview_server_hardware" "hv1" {
 name = "hv1.fqdn.cloud"
}

data "oneview_server_profile_template" "DL380_Gen9_1_spt" {
 name = "${upper(var.nlc_env)}_DL380_Gen9_1_spt"
}

resource "oneview_server_profile" "hv1_profile" {
  name = "hv1.fqdn.cloud"
  hardware_name = data.oneview_server_hardware.hv1.name
  server_hardware_type = data.oneview_server_profile_template.DL380_Gen9_1_spt.server_hardware_type
  template = data.oneview_server_profile_template.DL380_Gen9_1_spt.uri
  scopes_uri = data.oneview_scope.scope.uri
}
```

Debug log when I try to apply 
- omitted lines with "(known after apply)"
- changed some variable names etc

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # oneview_server_profile.hv_profile will be created
  + resource "oneview_server_profile" "hv_profile" {
      + hardware_name                 = "hv1.fqdn.cloud"
      + name                          = "hv1.fqdn.cloud"
      + scopes_uri                    = "/rest/scopes/e6971a0e-22cb-451f-8e7a-ec9138931199"
      + server_hardware_type          = "DL380 Gen9 1"
      + template                      = "/rest/server-profile-templates/c7f63d59-5c7f-4d81-a200-c250c2c4ce97"
      + update_type                   = "put"

< removed all lines with: (known after apply) >

Plan: 1 to add, 0 to change, 0 to destroy.
2021-12-21T07:27:29.508-0500 [DEBUG] command: asking for input: "\nDo you want to perform these actions?"

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

2021-12-21T07:27:30.979-0500 [INFO]  backend/local: apply calling Apply
2021-12-21T07:27:30.979-0500 [DEBUG] Building and walking apply graph for NormalMode plan
2021-12-21T07:27:30.979-0500 [DEBUG] Resource state not found for node "oneview_server_profile.hv_profile", instance oneview_server_profile.hv_profile
2021-12-21T07:27:30.979-0500 [DEBUG] ProviderTransformer: "data.oneview_server_profile_template.DL380_Gen9_1_spt (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hewlettpackard/oneview"]
2021-12-21T07:27:30.979-0500 [DEBUG] ProviderTransformer: "data.oneview_server_hardware.hv1 (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hewlettpackard/oneview"]
2021-12-21T07:27:30.979-0500 [DEBUG] ProviderTransformer: "oneview_server_profile.hv_profile (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hewlettpackard/oneview"]
2021-12-21T07:27:30.979-0500 [DEBUG] ProviderTransformer: "data.oneview_scope.scope (expand)" (*terraform.nodeExpandApplyableResource) needs provider["registry.terraform.io/hewlettpackard/oneview"]
2021-12-21T07:27:30.979-0500 [DEBUG] ProviderTransformer: "oneview_server_profile.hv_profile" (*terraform.NodeApplyableResourceInstance) needs provider["registry.terraform.io/hewlettpackard/oneview"]
2021-12-21T07:27:30.979-0500 [DEBUG] ReferenceTransformer: "var.ov_password" references: []
2021-12-21T07:27:30.979-0500 [DEBUG] ReferenceTransformer: "var.ov_api_version" references: []
2021-12-21T07:27:30.979-0500 [DEBUG] ReferenceTransformer: "var.ov_ssl_enabled" references: []
2021-12-21T07:27:30.979-0500 [DEBUG] ReferenceTransformer: "data.oneview_server_profile_template.DL380_Gen9_1_spt (expand)" references: []
2021-12-21T07:27:30.979-0500 [DEBUG] ReferenceTransformer: "var.ov_username" references: []
2021-12-21T07:27:30.979-0500 [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/hewlettpackard/oneview\"]" references: [var.ov_ssl_enabled var.ov_username var.ov_api_version local.ov_endpoint (expand) var.ov_password]
2021-12-21T07:27:30.979-0500 [DEBUG] ReferenceTransformer: "data.oneview_server_hardware.hv1 (expand)" references: []
2021-12-21T07:27:30.979-0500 [DEBUG] ReferenceTransformer: "data.oneview_scope.scope (expand)" references: []
2021-12-21T07:27:30.979-0500 [DEBUG] ReferenceTransformer: "var.x_env" references: []
2021-12-21T07:27:30.980-0500 [DEBUG] ReferenceTransformer: "var.domain_scope" references: []
2021-12-21T07:27:30.980-0500 [DEBUG] ReferenceTransformer: "oneview_server_profile.hv_profile (expand)" references: []
2021-12-21T07:27:30.980-0500 [DEBUG] ReferenceTransformer: "local.ov_endpoint (expand)" references: [var.mgt_subnet]
2021-12-21T07:27:30.980-0500 [DEBUG] ReferenceTransformer: "oneview_server_profile.hv_profile" references: [data.oneview_server_hardware.hv1 (expand) data.oneview_scope.scope (expand) data.oneview_server_profile_template.DL380_Gen9_1_spt (expand) data.oneview_server_profile_template.DL380_Gen9_1_spt (expand)]
2021-12-21T07:27:30.980-0500 [DEBUG] ReferenceTransformer: "var.mgt_subnet" references: []
2021-12-21T07:27:30.980-0500 [DEBUG] Starting graph walk: walkApply
2021-12-21T07:27:30.981-0500 [DEBUG] created provider logger: level=debug
2021-12-21T07:27:30.981-0500 [INFO]  provider: configuring client automatic mTLS
2021-12-21T07:27:30.991-0500 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/hewlettpackard/oneview/6.4.0-13/linux_amd64/terraform-provider-oneview_v6.4.0-13 args=[.terraform/providers/registry.terraform.io/hewlettpackard/oneview/6.4.0-13/linux_amd64/terraform-provider-oneview_v6.4.0-13]
2021-12-21T07:27:30.992-0500 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/hewlettpackard/oneview/6.4.0-13/linux_amd64/terraform-provider-oneview_v6.4.0-13 pid=32691
2021-12-21T07:27:30.992-0500 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/hewlettpackard/oneview/6.4.0-13/linux_amd64/terraform-provider-oneview_v6.4.0-13
2021-12-21T07:27:31.001-0500 [INFO]  provider.terraform-provider-oneview_v6.4.0-13: configuring server automatic mTLS: timestamp=2021-12-21T07:27:31.000-0500
2021-12-21T07:27:31.024-0500 [DEBUG] provider.terraform-provider-oneview_v6.4.0-13: plugin address: address=/tmp/plugin023093680 network=unix timestamp=2021-12-21T07:27:31.024-0500
2021-12-21T07:27:31.024-0500 [DEBUG] provider: using plugin: version=5
2021-12-21T07:27:31.062-0500 [DEBUG] No provider meta schema returned
2021-12-21T07:27:31.095-0500 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/hewlettpackard/oneview\"]" changed the config value, but that value is unused
2021-12-21T07:27:31.152-0500 [WARN]  Provider "registry.terraform.io/hewlettpackard/oneview" produced an invalid plan for oneview_server_profile.hv_profile, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .update_type: planned value cty.StringVal("put") for a non-computed attribute
      - .firmware: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
      - .local_storage: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
      - .san_storage: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
      - .volume_attachments: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
      - .boot_mode: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
      - .boot: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
      - .connection_settings: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
      - .management_processor: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
      - .os_deployment_settings: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
      - .bios_option: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead
oneview_server_profile.hv_profile: Creating...
2021-12-21T07:27:31.152-0500 [INFO]  Starting apply for oneview_server_profile.hv_profile
2021-12-21T07:27:31.154-0500 [DEBUG] oneview_server_profile.hv_profile: applying the planned Create change
2021-12-21T07:27:31.158-0500 [DEBUG] provider.terraform-provider-oneview_v6.4.0-13: 2021/12/21 07:27:31 [DEBUG] setting computed for "boot" from ComputedKeys
2021-12-21T07:27:31.158-0500 [DEBUG] provider.terraform-provider-oneview_v6.4.0-13: 2021/12/21 07:27:31 [DEBUG] setting computed for "management_processor" from ComputedKeys
2021-12-21T07:27:31.159-0500 [DEBUG] provider.terraform-provider-oneview_v6.4.0-13: 2021/12/21 07:27:31 [DEBUG] setting computed for "san_storage" from ComputedKeys
2021-12-21T07:27:31.159-0500 [DEBUG] provider.terraform-provider-oneview_v6.4.0-13: 2021/12/21 07:27:31 [DEBUG] setting computed for "volume_attachments" from ComputedKeys
2021-12-21T07:27:31.159-0500 [DEBUG] provider.terraform-provider-oneview_v6.4.0-13: 2021/12/21 07:27:31 [DEBUG] setting computed for "bios_option" from ComputedKeys
2021-12-21T07:27:31.159-0500 [DEBUG] provider.terraform-provider-oneview_v6.4.0-13: 2021/12/21 07:27:31 [DEBUG] setting computed for "os_deployment_settings" from ComputedKeys
2021-12-21T07:27:31.159-0500 [DEBUG] provider.terraform-provider-oneview_v6.4.0-13: 2021/12/21 07:27:31 [DEBUG] setting computed for "boot_mode" from ComputedKeys
2021-12-21T07:27:31.159-0500 [DEBUG] provider.terraform-provider-oneview_v6.4.0-13: 2021/12/21 07:27:31 [DEBUG] setting computed for "local_storage" from ComputedKeys
2021-12-21T07:27:31.159-0500 [DEBUG] provider.terraform-provider-oneview_v6.4.0-13: 2021/12/21 07:27:31 [DEBUG] setting computed for "firmware" from ComputedKeys
2021-12-21T07:27:31.159-0500 [DEBUG] provider.terraform-provider-oneview_v6.4.0-13: 2021/12/21 07:27:31 [DEBUG] setting computed for "connection_settings" from ComputedKeys
2021-12-21T07:27:31.168-0500 [ERROR] vertex "oneview_server_profile.hv_profile" error: Provider produced inconsistent result after apply
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to oneview_server_profile.hv_profile, provider "provider[\"registry.terraform.io/hewlettpackard/oneview\"]" produced an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
2021-12-21T07:27:31.171-0500 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-12-21T07:27:31.172-0500 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hewlettpackard/oneview/6.4.0-13/linux_amd64/terraform-provider-oneview_v6.4.0-13 pid=32691
2021-12-21T07:27:31.172-0500 [DEBUG] provider: plugin exited
```
Hopefully this gives more insight into this bug.

Doing this manually from the GUI works without trouble. Also had the browser network api calls open while I was doing it, and use these input hardcoded in my main.tf, but got the same result.

**Comment by BoudewijnSwen** [comment]
It seems that the first part of this issue, where it was destroying the local accounts part was fixed by merging the two `mp_settings` blocks.

I will remake a new issue for the 2nd issue, with applying the template to a profile. That one still persists unfortunately.
