### ISSUE TITLE
Logical Interconnect Group crash

### ISSUE THREAD

**Issue by adarobin** [HewlettPackard/terraform-provider-oneview#517]
It looks as though at some point the `fast_mac_cache_failover` attribute of `interconnect_settings` and several others under interconnect_settings were renamed without following [Terraform provider best practices](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/deprecations#renaming-an-optional-attribute).

It also appears that there are still references to `fast_mac_cache_failover` instead of `enable_fast_mac_cache_failover` in the code base which result in a crash.

This is on provider 8.1.0-13 with OneView 6.6.02 and API version 3800.

```
Stack trace from the terraform-provider-oneview_v8.1.0-13 plugin:

panic: interface conversion: interface {} is nil, not bool

goroutine 50 [running]:
github.com/HewlettPackard/terraform-provider-oneview/oneview.resourceLogicalInterconnectGroupUpdate(0xc00057b780, 0xdef6a0, 0xc000b162a0, 0x0, 0xffffffffffffffff)
	github.com/HewlettPackard/terraform-provider-oneview/oneview/resource_logical_interconnect_group.go:2938 +0xd159
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc00036d5c0, 0x106cf60, 0xc0005b6380, 0xc00057b780, 0xdef6a0, 0xc000b162a0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/resource.go:302 +0x88
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00036d5c0, 0x106cf60, 0xc0005b6380, 0xc000b0c310, 0xc0008cbda0, 0xdef6a0, 0xc000b162a0, 0x0, 0x0, 0x0, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/resource.go:404 +0x390
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0001ae480, 0x106cf60, 0xc0005b6380, 0xc0004a65a0, 0xc0005b6380, 0x0, 0x1076a60)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/grpc_provider.go:955 +0x8cf
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc0001d66a0, 0x106cf60, 0xc0005b6380, 0xc000b0c0e0, 0xc0001d66a0, 0xc00020dba0, 0x46b307)
	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:332 +0xae
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xeadee0, 0xc0001d66a0, 0x106d020, 0xc000b043f0, 0xc00056e1e0, 0x0, 0x106d020, 0xc000b043f0, 0xc0006f2000, 0x6421)
	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001f8fc0, 0x10749e0, 0xc0001ecd80, 0xc000132600, 0xc0003cd380, 0x14ef120, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc0001f8fc0, 0x10749e0, 0xc0001ecd80, 0xc000132600, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd05
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000418000, 0xc0001f8fc0, 0x10749e0, 0xc0001ecd80, 0xc000132600)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-oneview_v8.1.0-13 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by adarobin** [comment]
I reverted back to 7.1.0-13 to get around the issue for now.

**Comment by nabhajit-ray** [comment]
Thanks @adarobin , will check and get back to you on this

**Comment by nabhajit-ray** [comment]
This is fixed in latest release
