### ISSUE TITLE
Crash in logical interconnect group

### ISSUE THREAD

**Issue by adarobin** [HewlettPackard/terraform-provider-oneview#535]
There is still an issue with the logical interconnect group code related to #517 .  It appears that `enable_network_loop_protection` is set to TypeString instead of TypeBool.  This is resulting in a crash because that variable is assumed to be a boolean later in the code.

See https://github.com/HewlettPackard/terraform-provider-oneview/blob/68326a6315de423a769d42159da5cd4221d5c137/oneview/resource_logical_interconnect_group.go#L640
and 
https://github.com/HewlettPackard/terraform-provider-oneview/blob/68326a6315de423a769d42159da5cd4221d5c137/oneview/resource_logical_interconnect_group.go#L2943

```
Stack trace from the terraform-provider-oneview_v8.3.0-13 plugin:

panic: interface conversion: interface {} is string, not bool

goroutine 50 [running]:
github.com/HewlettPackard/terraform-provider-oneview/oneview.resourceLogicalInterconnectGroupUpdate(0xc0006d0600, 0xd9da40, 0xc000689500, 0x0, 0xffffffffffffffff)
	github.com/HewlettPackard/terraform-provider-oneview/oneview/resource_logical_interconnect_group.go:2943 +0xd13f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc00036f5c0, 0x100ef38, 0xc000483d80, 0xc0006d0600, 0xd9da40, 0xc000689500, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/resource.go:302 +0x88
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00036f5c0, 0x100ef38, 0xc000483d80, 0xc0000d4770, 0xc0004ef8a0, 0xd9da40, 0xc000689500, 0x0, 0x0, 0x0, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/resource.go:404 +0x390
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000d1b8, 0x100ef38, 0xc000483d80, 0xc0008839a0, 0xc000483d80, 0xe574c0, 0xc000625800)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc00006bde0, 0x100efe0, 0xc000483d80, 0xc0000d4690, 0xc00006bde0, 0xc000625890, 0xc000a2aba0)
	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xe574c0, 0xc00006bde0, 0x100efe0, 0xc000625890, 0xc00049a060, 0x0, 0x100efe0, 0xc000625890, 0xc000505500, 0x294b)
	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001f8e00, 0x1015ed8, 0xc000a32d80, 0xc00058e100, 0xc0003cb380, 0x145ce80, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001f8e00, 0x1015ed8, 0xc000a32d80, 0xc00058e100, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00041c190, 0xc0001f8e00, 0x1015ed8, 0xc000a32d80, 0xc00058e100)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-oneview_v8.3.0-13 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by nabhajit-ray** [comment]
Thanks @adarobin . Will fix that.

**Comment by nabhajit-ray** [comment]
this is fixed in main branch
