### ISSUE TITLE
Terraform crash while deploying OS through image streamer 

### ISSUE THREAD

**Issue by SoibamRepo** [HewlettPackard/terraform-provider-oneview#99]
Here is terraform code for  deploying OS using Image streamer deployment plan  and it gives "terraform crash"

resource "oneview_server_profile" "test" {
     count           = 1
     name            = "terraform-test-${count.index}"
     template = "terraform-server-profile-template"
     hardware_name        = "MXQ71906MB, bay 1"
     type = "ServerProfileV10"
   }

resource "oneview_i3s_plan" "test" {
     count = 1
     server_name = "${oneview_server_profile.test.name}"
     os_deployment_plan = "Terraform-ESXI"
     deploy_net_name = "DEPLOY"
   }

**Crash messages**

panic: runtime error: index out of range
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview:
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview: goroutine 51 [running]:
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview: github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/HewlettPackard/oneview-golang/ov.(*OVClient).ManageI3SConnections(0xc0001a3440, 0x0, 0x0, 0x0, 0xc0003d5dd0, 0x6, 0x0, 0x0, 0xc00045c200, 0x13, ...)
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview:         /root/go/src/github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/HewlettPackard/oneview-golang/ov/connectionv3.go:89 +0x13ca
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview: github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/HewlettPackard/oneview-golang/ov.(*OVClient).CustomizeServer(0xc0001a3440, 0xc0003d5da0, 0x10, 0xc0003d5db0, 0xe, 0x0, 0xc0003d5dd0, 0x6, 0xc0000529c0, 0x910ea4)
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview:         /root/go/src/github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/HewlettPackard/oneview-golang/ov/profilesv3.go:135 +0x59a
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview: github.com/HewlettPackard/terraform-provider-oneview/oneview.resourceI3SPlanCreate(0xc0003d8770, 0xaa9a00, 0xc0001482a0, 0x0, 0x0)
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview:         /root/go/src/github.com/HewlettPackard/terraform-provider-oneview/oneview/resource_i3s_plan.go:85 +0x513
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview: github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0002d57a0, 0xc0000ab950, 0xc00040d660, 0xaa9a00, 0xc0001482a0, 0x40d301, 0xc000052b80, 0x49150c)
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview:         /root/go/src/github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:186 +0x385
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview: github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0001695e0, 0xc0000ab900, 0xc0000ab950, 0xc00040d660, 0xc000046700, 0x18, 0x7f0c5a12f6c0)
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview:         /root/go/src/github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:242 +0x9c
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview: github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc00033edc0, 0xc00040d600, 0xc000420ea0, 0x0, 0x0)
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview:         /root/go/src/github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview: reflect.Value.call(0xc00006df80, 0xc00000ef40, 0x13, 0xb57828, 0x4, 0xc000052f18, 0x3, 0x3, 0xc00019ec80, 0x414d37, ...)
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview:         /usr/local/go/src/reflect/value.go:447 +0x449
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview: reflect.Value.Call(0xc00006df80, 0xc00000ef40, 0x13, 0xc000044f18, 0x3, 0x3, 0x12a05f200, 0xc000044f28, 0x42b1a2)
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview:         /usr/local/go/src/reflect/value.go:308 +0xa4
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview: net/rpc.(*service).call(0xc0002b1a80, 0xc0001ed220, 0xc0000256b0, 0xc0000256c0, 0xc0001eb600, 0xc0002d9c60, 0xa2f220, 0xc00040d600, 0x16, 0xa2f260, ...)
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview:         /usr/local/go/src/net/rpc/server.go:384 +0x14e
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview: created by net/rpc.(*Server).ServeCodec
2019-06-06T04:02:12.323-0500 [DEBUG] plugin.terraform-provider-oneview:         /usr/local/go/src/net/rpc/server.go:481 +0x47e
2019/06/06 04:02:12 [TRACE] root: eval: *terraform.EvalWriteState
2019/06/06 04:02:12 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2019/06/06 04:02:12 [TRACE] root: eval: *terraform.EvalIf
2019/06/06 04:02:12 [TRACE] root: eval: *terraform.EvalWriteState
2019/06/06 04:02:12 [TRACE] root: eval: *terraform.EvalWriteDiff
2019/06/06 04:02:12 [TRACE] root: eval: *terraform.EvalApplyPost
2019/06/06 04:02:12 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* oneview_i3s_plan.test: unexpected EOF
2019/06/06 04:02:12 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* oneview_i3s_plan.test: unexpected EOF
2019/06/06 04:02:12 [TRACE] [walkApply] Exiting eval tree: oneview_i3s_plan.test
2019/06/06 04:02:12 [TRACE] dag/walk: upstream errored, not walking "provider.oneview (close)"
2019/06/06 04:02:12 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2019/06/06 04:02:12 [TRACE] dag/walk: upstream errored, not walking "root"
2019/06/06 04:02:12 [TRACE] Preserving existing state lineage "c092cb80-09e4-986f-e0bc-1a30578a6e29"
2019/06/06 04:02:12 [TRACE] Preserving existing state lineage "c092cb80-09e4-986f-e0bc-1a30578a6e29"
2019/06/06 04:02:12 [TRACE] Preserving existing state lineage "c092cb80-09e4-986f-e0bc-1a30578a6e29"
2019-06-06T04:02:12.325-0500 [DEBUG] plugin: plugin process exited: path=/root/go/src/github.com/HewlettPackard/terraform-provider-oneview/terraform-provider-oneview
2019/06/06 04:02:12 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-06-06T04:02:12.335-0500 [WARN ] plugin: error closing client during Kill: err="connection is shut down"

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
[root@localhost terraform-provider-oneview]#

**Comment by madhav-bharadwaj** [comment]
Closing this issue and referencing it to the i3s resource enhancement in https://github.com/HewlettPackard/terraform-provider-oneview/issues/107.
